// This file was generated by @synthql/backend
import { query } from "@synthql/queries";
export const db = {
  "public.actor": {
    name: "public.actor",
    columns: {
      actor_id: {
        name: "actor_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      first_name: {
        name: "first_name",
        nullable: false,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      last_name: {
        name: "last_name",
        nullable: false,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      last_update: {
        name: "last_update",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["actor_id"],
  },
  "public.actor_info": {
    name: "public.actor_info",
    columns: {
      actor_id: {
        name: "actor_id",
        nullable: true,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      film_info: {
        name: "film_info",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      first_name: {
        name: "first_name",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      last_name: {
        name: "last_name",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
    },
  },
  "public.address": {
    name: "public.address",
    columns: {
      address_id: {
        name: "address_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      city_id: {
        name: "city_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      address: {
        name: "address",
        nullable: false,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      address2: {
        name: "address2",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      district: {
        name: "district",
        nullable: false,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      phone: {
        name: "phone",
        nullable: false,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      postal_code: {
        name: "postal_code",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      last_update: {
        name: "last_update",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["address_id"],
  },
  "public.category": {
    name: "public.category",
    columns: {
      category_id: {
        name: "category_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      name: {
        name: "name",
        nullable: false,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      last_update: {
        name: "last_update",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["category_id"],
  },
  "public.city": {
    name: "public.city",
    columns: {
      city_id: {
        name: "city_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      country_id: {
        name: "country_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      city: {
        name: "city",
        nullable: false,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      last_update: {
        name: "last_update",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["city_id"],
  },
  "public.country": {
    name: "public.country",
    columns: {
      country_id: {
        name: "country_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      country: {
        name: "country",
        nullable: false,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      last_update: {
        name: "last_update",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["country_id"],
  },
  "public.customer": {
    name: "public.customer",
    columns: {
      activebool: {
        name: "activebool",
        nullable: false,
        type: {
          name: "bool",
          schema: "pg_catalog",
        },
      },
      create_date: {
        name: "create_date",
        nullable: false,
        type: {
          name: "date",
          schema: "pg_catalog",
        },
      },
      active: {
        name: "active",
        nullable: true,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      address_id: {
        name: "address_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      customer_id: {
        name: "customer_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      store_id: {
        name: "store_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      email: {
        name: "email",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      first_name: {
        name: "first_name",
        nullable: false,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      last_name: {
        name: "last_name",
        nullable: false,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      last_update: {
        name: "last_update",
        nullable: true,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["customer_id"],
  },
  "public.customer_list": {
    name: "public.customer_list",
    columns: {
      id: {
        name: "id",
        nullable: true,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      sid: {
        name: "sid",
        nullable: true,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      address: {
        name: "address",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      city: {
        name: "city",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      country: {
        name: "country",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      name: {
        name: "name",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      notes: {
        name: "notes",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      phone: {
        name: "phone",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      "zip code": {
        name: "zip code",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
    },
  },
  "public.film": {
    name: "public.film",
    columns: {
      length: {
        name: "length",
        nullable: true,
        type: {
          name: "int2",
          schema: "pg_catalog",
        },
      },
      rental_duration: {
        name: "rental_duration",
        nullable: false,
        type: {
          name: "int2",
          schema: "pg_catalog",
        },
      },
      film_id: {
        name: "film_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      language_id: {
        name: "language_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      original_language_id: {
        name: "original_language_id",
        nullable: true,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      release_year: {
        name: "release_year",
        nullable: true,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      rating: {
        name: "rating",
        nullable: true,
        type: {
          name: "mpaa_rating",
          schema: "public",
        },
      },
      rental_rate: {
        name: "rental_rate",
        nullable: false,
        type: {
          name: "numeric",
          schema: "pg_catalog",
        },
      },
      replacement_cost: {
        name: "replacement_cost",
        nullable: false,
        type: {
          name: "numeric",
          schema: "pg_catalog",
        },
      },
      special_features: {
        name: "special_features",
        nullable: true,
        type: {
          name: "_text",
          schema: "pg_catalog",
        },
      },
      description: {
        name: "description",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      title: {
        name: "title",
        nullable: false,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      last_update: {
        name: "last_update",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
      fulltext: {
        name: "fulltext",
        nullable: false,
        type: {
          name: "tsvector",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["film_id"],
  },
  "public.film_actor": {
    name: "public.film_actor",
    columns: {
      actor_id: {
        name: "actor_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      film_id: {
        name: "film_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      last_update: {
        name: "last_update",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["actor_id", "film_id"],
  },
  "public.film_category": {
    name: "public.film_category",
    columns: {
      category_id: {
        name: "category_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      film_id: {
        name: "film_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      last_update: {
        name: "last_update",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["category_id", "film_id"],
  },
  "public.film_list": {
    name: "public.film_list",
    columns: {
      length: {
        name: "length",
        nullable: true,
        type: {
          name: "int2",
          schema: "pg_catalog",
        },
      },
      fid: {
        name: "fid",
        nullable: true,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      rating: {
        name: "rating",
        nullable: true,
        type: {
          name: "mpaa_rating",
          schema: "public",
        },
      },
      price: {
        name: "price",
        nullable: true,
        type: {
          name: "numeric",
          schema: "pg_catalog",
        },
      },
      actors: {
        name: "actors",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      category: {
        name: "category",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      description: {
        name: "description",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      title: {
        name: "title",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
    },
  },
  "public.inventory": {
    name: "public.inventory",
    columns: {
      film_id: {
        name: "film_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      inventory_id: {
        name: "inventory_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      store_id: {
        name: "store_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      last_update: {
        name: "last_update",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["inventory_id"],
  },
  "public.language": {
    name: "public.language",
    columns: {
      name: {
        name: "name",
        nullable: false,
        type: {
          name: "bpchar",
          schema: "pg_catalog",
        },
      },
      language_id: {
        name: "language_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      last_update: {
        name: "last_update",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["language_id"],
  },
  "public.nicer_but_slower_film_list": {
    name: "public.nicer_but_slower_film_list",
    columns: {
      length: {
        name: "length",
        nullable: true,
        type: {
          name: "int2",
          schema: "pg_catalog",
        },
      },
      fid: {
        name: "fid",
        nullable: true,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      rating: {
        name: "rating",
        nullable: true,
        type: {
          name: "mpaa_rating",
          schema: "public",
        },
      },
      price: {
        name: "price",
        nullable: true,
        type: {
          name: "numeric",
          schema: "pg_catalog",
        },
      },
      actors: {
        name: "actors",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      category: {
        name: "category",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      description: {
        name: "description",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      title: {
        name: "title",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
    },
  },
  "public.payment": {
    name: "public.payment",
    columns: {
      customer_id: {
        name: "customer_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      payment_id: {
        name: "payment_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      rental_id: {
        name: "rental_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      staff_id: {
        name: "staff_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      amount: {
        name: "amount",
        nullable: false,
        type: {
          name: "numeric",
          schema: "pg_catalog",
        },
      },
      payment_date: {
        name: "payment_date",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["payment_date", "payment_id"],
  },
  "public.payment_p2022_01": {
    name: "public.payment_p2022_01",
    columns: {
      customer_id: {
        name: "customer_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      payment_id: {
        name: "payment_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      rental_id: {
        name: "rental_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      staff_id: {
        name: "staff_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      amount: {
        name: "amount",
        nullable: false,
        type: {
          name: "numeric",
          schema: "pg_catalog",
        },
      },
      payment_date: {
        name: "payment_date",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["payment_date", "payment_id"],
  },
  "public.payment_p2022_02": {
    name: "public.payment_p2022_02",
    columns: {
      customer_id: {
        name: "customer_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      payment_id: {
        name: "payment_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      rental_id: {
        name: "rental_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      staff_id: {
        name: "staff_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      amount: {
        name: "amount",
        nullable: false,
        type: {
          name: "numeric",
          schema: "pg_catalog",
        },
      },
      payment_date: {
        name: "payment_date",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["payment_date", "payment_id"],
  },
  "public.payment_p2022_03": {
    name: "public.payment_p2022_03",
    columns: {
      customer_id: {
        name: "customer_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      payment_id: {
        name: "payment_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      rental_id: {
        name: "rental_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      staff_id: {
        name: "staff_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      amount: {
        name: "amount",
        nullable: false,
        type: {
          name: "numeric",
          schema: "pg_catalog",
        },
      },
      payment_date: {
        name: "payment_date",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["payment_date", "payment_id"],
  },
  "public.payment_p2022_04": {
    name: "public.payment_p2022_04",
    columns: {
      customer_id: {
        name: "customer_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      payment_id: {
        name: "payment_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      rental_id: {
        name: "rental_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      staff_id: {
        name: "staff_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      amount: {
        name: "amount",
        nullable: false,
        type: {
          name: "numeric",
          schema: "pg_catalog",
        },
      },
      payment_date: {
        name: "payment_date",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["payment_date", "payment_id"],
  },
  "public.payment_p2022_05": {
    name: "public.payment_p2022_05",
    columns: {
      customer_id: {
        name: "customer_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      payment_id: {
        name: "payment_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      rental_id: {
        name: "rental_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      staff_id: {
        name: "staff_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      amount: {
        name: "amount",
        nullable: false,
        type: {
          name: "numeric",
          schema: "pg_catalog",
        },
      },
      payment_date: {
        name: "payment_date",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["payment_date", "payment_id"],
  },
  "public.payment_p2022_06": {
    name: "public.payment_p2022_06",
    columns: {
      customer_id: {
        name: "customer_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      payment_id: {
        name: "payment_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      rental_id: {
        name: "rental_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      staff_id: {
        name: "staff_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      amount: {
        name: "amount",
        nullable: false,
        type: {
          name: "numeric",
          schema: "pg_catalog",
        },
      },
      payment_date: {
        name: "payment_date",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["payment_date", "payment_id"],
  },
  "public.payment_p2022_07": {
    name: "public.payment_p2022_07",
    columns: {
      customer_id: {
        name: "customer_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      payment_id: {
        name: "payment_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      rental_id: {
        name: "rental_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      staff_id: {
        name: "staff_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      amount: {
        name: "amount",
        nullable: false,
        type: {
          name: "numeric",
          schema: "pg_catalog",
        },
      },
      payment_date: {
        name: "payment_date",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["payment_date", "payment_id"],
  },
  "public.rental": {
    name: "public.rental",
    columns: {
      customer_id: {
        name: "customer_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      inventory_id: {
        name: "inventory_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      rental_id: {
        name: "rental_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      staff_id: {
        name: "staff_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      last_update: {
        name: "last_update",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
      rental_date: {
        name: "rental_date",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
      return_date: {
        name: "return_date",
        nullable: true,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["rental_id"],
  },
  "public.sales_by_film_category": {
    name: "public.sales_by_film_category",
    columns: {
      total_sales: {
        name: "total_sales",
        nullable: true,
        type: {
          name: "numeric",
          schema: "pg_catalog",
        },
      },
      category: {
        name: "category",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
    },
  },
  "public.sales_by_store": {
    name: "public.sales_by_store",
    columns: {
      total_sales: {
        name: "total_sales",
        nullable: true,
        type: {
          name: "numeric",
          schema: "pg_catalog",
        },
      },
      manager: {
        name: "manager",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      store: {
        name: "store",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
    },
  },
  "public.staff": {
    name: "public.staff",
    columns: {
      active: {
        name: "active",
        nullable: false,
        type: {
          name: "bool",
          schema: "pg_catalog",
        },
      },
      picture: {
        name: "picture",
        nullable: true,
        type: {
          name: "bytea",
          schema: "pg_catalog",
        },
      },
      address_id: {
        name: "address_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      staff_id: {
        name: "staff_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      store_id: {
        name: "store_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      email: {
        name: "email",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      first_name: {
        name: "first_name",
        nullable: false,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      last_name: {
        name: "last_name",
        nullable: false,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      password: {
        name: "password",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      username: {
        name: "username",
        nullable: false,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      last_update: {
        name: "last_update",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["staff_id"],
  },
  "public.staff_list": {
    name: "public.staff_list",
    columns: {
      id: {
        name: "id",
        nullable: true,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      sid: {
        name: "sid",
        nullable: true,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      address: {
        name: "address",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      city: {
        name: "city",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      country: {
        name: "country",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      name: {
        name: "name",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      phone: {
        name: "phone",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
      "zip code": {
        name: "zip code",
        nullable: true,
        type: {
          name: "text",
          schema: "pg_catalog",
        },
      },
    },
  },
  "public.store": {
    name: "public.store",
    columns: {
      address_id: {
        name: "address_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      manager_staff_id: {
        name: "manager_staff_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      store_id: {
        name: "store_id",
        nullable: false,
        type: {
          name: "int4",
          schema: "pg_catalog",
        },
      },
      last_update: {
        name: "last_update",
        nullable: false,
        type: {
          name: "timestamptz",
          schema: "pg_catalog",
        },
      },
    },
    primaryKey: ["store_id"],
  },
} as const;

type AllNumberTypes = {
  schema: "pg_catalog";
  name: "int2" | "int4" | "numeric";
};

interface AllStringTypes {
  schema: "pg_catalog";
  name:
    | "text"
    | "varchar"
    | "bpchar"
    | "bytea"
    | "bpchar"
    | "uuid"
    | "int8"
    | "tsvector";
}

interface AllBoolTypes {
  schema: "pg_catalog";
  name: "bool";
}

interface AllDateTypes {
  schema: "pg_catalog";
  name: "date" | "timestamptz";
}

type ConvertPgType<T> = T extends AllNumberTypes
  ? number
  : T extends AllStringTypes
    ? string
    : T extends AllBoolTypes
      ? boolean
      : T extends AllDateTypes
        ? Date
        : [unknown, T];

type InferColumn<T> =
  // Nullable check
  T extends { nullable: true; type: infer Type }
    ? null | ConvertPgType<Type>
    : T extends { type: infer Type }
      ? ConvertPgType<Type>
      : never;

type InferTable<T> = T extends { columns: infer C }
  ? { [column in keyof C]: InferColumn<C[column]> }
  : never;

type InferDB<T> = {
  [table in keyof T]: InferTable<T[table]>;
};

export type DB = InferDB<typeof db>;
export const from = query<DB>().from;
